CREATE TABLE users (
  UserID SERIAL PRIMARY KEY,
  firstName VARCHAR NOT NULL,
  lastName VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  pw VARCHAR NOT NULL,
  place VARCHAR NOT NULL
);

CREATE TABLE users_staff (
  UserID2 SERIAL PRIMARY KEY,
  firstName2 VARCHAR NOT NULL,
  lastName2 VARCHAR NOT NULL,
  email2 VARCHAR NOT NULL,
  pw2 VARCHAR NOT NULL,
  place2 VARCHAR NOT NULL,
  shelter2 VARCHAR NOT NULL
);

CREATE TABLE illinois (
    AnimalID SERIAL PRIMARY KEY,
    AnimalType VARCHAR  NOT NULL,
    AnimalBreed VARCHAR NOT NULL,
    AnimalName VARCHAR NOT NULL,
    Age INTEGER NOT NULL,
    Medical VARCHAR NOT NULL,
    Exercise VARCHAR NOT NULL,
    OtherNeeds VARCHAR NOT NULL
);

CREATE TABLE arizona (
    AnimalID SERIAL PRIMARY KEY,
    AnimalType VARCHAR  NOT NULL,
    AnimalBreed VARCHAR NOT NULL,
    AnimalName VARCHAR NOT NULL,
    Age INTEGER NOT NULL,
    Medical VARCHAR NOT NULL,
    Exercise VARCHAR NOT NULL,
    OtherNeeds VARCHAR NOT NULL
);

CREATE TABLE california (
    AnimalID SERIAL PRIMARY KEY,
    AnimalType VARCHAR  NOT NULL,
    AnimalBreed VARCHAR NOT NULL,
    AnimalName VARCHAR NOT NULL,
    Age INTEGER NOT NULL,
    Medical VARCHAR NOT NULL,
    Exercise VARCHAR NOT NULL,
    OtherNeeds VARCHAR NOT NULL
);




