CREATE TABLE users (
  UserID SERIAL PRIMARY KEY,
  firstName VARCHAR NOT NULL,
  lastName VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password1 VARCHAR NOT NULL,
);
CREATE TABLE users_staff (
  UserID2 SERIAL PRIMARY KEY,
  shelter VARCHAR NOT NULL,
  email2 VARCHAR NOT NULL,
  password2 VARCHAR NOT NULL,
  shelter VARHCAR NOT NULL,
);
CREATE TABLE arizona (
    ID SERIAL PRIMARY KEY,
    AnimalName VARCHAR NOT NULL,
    Age INTEGER NOT NULL, 
    Gender VARCHAR NOT NULL,
    Breed VARCHAR  NOT NULL,
    AnimalType VARCHAR NOT NULL,
    Needs VARCHAR,
);

CREATE TABLE illinois (
    ID SERIAL PRIMARY KEY,
    AnimalName VARCHAR  NOT NULL,
    Age INTEGER NOT NULL,
    AnimalWeight INTEGER NOT NULL, 
    Gender VARCHAR NOT NULL,
    Breed VARCHAR NOT NULL,
    AnimalType VARCHAR NOT NULL,
    Needs VARCHAR,
);

CREATE TABLE california (
    ID SERIAL PRIMARY KEY,
    AnimalName VARCHAR NOT NULL, 
    Age INTEGER NOT NULL,
    AnimalWeight INTEGER NOT NULL,
    Gender VARCHAR NOT NULL,
    Breed VARCHAR NOT NULL,
    AnimalType VARCHAR NOT NULL,
    Needs VARCHAR,
);


